guest1 = Guest.create("Laurie", "Florida")
guest2 = Guest.create("Kat", "Los Angelos")
guest3 = Guest.create("Patty", "Brooklyn")


hotel1 = Hotel.create("The Blue Lagoon", "Fhloston Paradise", "Andromeda", "High of 99, low of 85", "The Mermaid Inn")
hotel2 = Hotel.create("The Lightening Tower", "Valhalla", "Asgard", "High of 75, low of 65", "Loki's Tavern")
hotel3 = Hotel.create("Hometree", "Pandora", "Messier 81", "High of 110, low of 100", "Fig")
hotel4 = Hotel.create("Junglehouse", "Antila", "Vanaheim", "High of 65, low 0f 45", "Gourmet Garden")
hotel5 = Hotel.create("The Camila", "Proxima", "Alpha Centuri", "High of 85, low of 80", "Chew")
hotel6 = Hotel.create("Linden House", "Saturn", "High 25, low of -15", "Milky Way", "Fisherman's Cove")

booking1 = Booking.create(guest1, hotel1)
booking2 = Booking.create(guest2, hotel1)
booking3 = Booking.create(guest3, hotel2)
booking4 = Booking.create(guest3, hotel1)
booking5 = Booking.create(guest1, hotel6)
booking6 = Booking.create(guest1, hotel1)
booking7 = Booking.create(guest2, hotel3)
booking8 = Booking.create(guest3, hotel4)
